apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-sensors
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: spring-sensors
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  params:
  - name: testing_pipeline_matching_labels
    value:
      apps.tanzu.vmware.com/pipeline: test
      apps.tanzu.vmware.com/language: java
      apps.tanzu.vmware.com/pipeline: jenkins-pipeline
  - name: testing_pipeline_params
    value:
      job-name: maven_test
      secret-name: jenkins-tls
      job-params: "[{\"name\":\"GIT-URL\",\"value\":\"https://github.com/dsharmaa4/spring-sensors\"},{\"name\":\"GIT-BRANCH\",\"value\":\"main\"}]"
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/dsharmaa4/spring-sensors
      ref:
        branch: main
